name: 100% Auto Product Machine

on:
  workflow_dispatch: # рдЕрднреА рд╣рд╛рде рд╕реЗ рдЪрд▓рд╛рдиреЗ рдХреЗ рд▓рд┐рдП
  schedule:
    - cron: '0 10 * * *' # рд╣рд░ рджрд┐рди рд╕реБрдмрд╣ 10:00 рдмрдЬреЗ рдЕрдкрдиреЗ рдЖрдк рдЪрд▓реЗрдЧрд╛

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Product and Publish
        run: |
          # 1. рдЖрдЬ рдХрд╛ рдЯреНрд░реЗрдВрдбрд┐рдВрдЧ рдЯреЙрдкрд┐рдХ рдФрд░ рдХрдВрдЯреЗрдВрдЯ (AI Solutions for Small Business)
          PRODUCT_NAME="AI Business Growth Kit 2026"
          PRODUCT_PRICE=1500 # рдХреАрдордд (рдкреИрд╕реЗ рдореЗрдВ, рдпрд╛рдиреА 15.00 USD)
          DESCRIPTION="рдпрд╣ рдПрдХ рдкреНрд░реАрдорд┐рдпрдо рдЧрд╛рдЗрдб рд╣реИ рдЬреЛ рдЖрдкрдХреЗ рдЫреЛрдЯреЗ рдмрд┐рдЬрдиреЗрд╕ рдХреЛ AI рдХреА рдорджрдж рд╕реЗ 10x рд╕реНрдХреЗрд▓ рдХрд░рдиреЗ рдореЗрдВ рдорджрдж рдХрд░реЗрдЧреАред"

          # 2. Gumroad рдкрд░ рдкреНрд░реЛрдбрдХреНрдЯ рдкрдмреНрд▓рд┐рд╢ рдХрд░рдирд╛
          RESPONSE=$(curl -s -X POST https://api.gumroad.com/v2/products \
            -d "access_token=${{ secrets.GUMROAD_TOKEN }}" \
            -d "name=$PRODUCT_NAME" \
            -d "price=$PRODUCT_PRICE" \
            -d "description=$DESCRIPTION" \
            -d "published=true")

          # 3. рдЯреЗрд▓реАрдЧреНрд░рд╛рдо рдкрд░ рдорд╛рд░реНрдХреЗрдЯрд┐рдВрдЧ рдореИрд╕реЗрдЬ рднреЗрдЬрдирд╛
          PRODUCT_URL=$(echo $RESPONSE | jq -r '.product.short_url')
          
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="ЁЯЪА *рдирдпрд╛ рдкреНрд░реАрдорд┐рдпрдо рдкреНрд░реЛрдбрдХреНрдЯ рд▓рд╛рдЗрд╡!* %0A%0AЁЯУж рдирд╛рдо: $PRODUCT_NAME %0AЁЯТ░ рдХреАрдордд: $15 %0AЁЯФЧ рдЕрднреА рдЦрд░реАрджреЗрдВ: $PRODUCT_URL %0A%0AтЬЕ рдпрд╣ рдореИрд╕реЗрдЬ рдСрдЯреЛрдореИрдЯрд┐рдХ рдорд╢реАрди рджреНрд╡рд╛рд░рд╛ рднреЗрдЬрд╛ рдЧрдпрд╛ рд╣реИред" \
          -d parse_mode="Markdown"
